config/routes.rb
Rails.application.routes.draw do
  
  
  root "homes#splash"
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: [:show] do
    resources :expenses
    resources :categories
  end
  resources :categories
  resources :expenses
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, length: { maximum: 35, minimum: 2 }, uniqueness: true
  validates :icon, presence: true

  belongs_to :user, foreign_key: 'author_id'
  has_and_belongs_to_many :expenses

  ICONS = %i[alarm calls database droplet energy fare fire food fuel health
             mic-fill mortarboard rent tools personal container ].freeze
end

app/models/expense.rb
class Expense < ApplicationRecord
  validates :name, presence: true
  validates :amount, presence: true,
                     numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  belongs_to :user, foreign_key: 'author_id'

  has_and_belongs_to_many :categories
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true

  has_many :categories, foreign_key: 'author_id', dependent: :destroy
  has_many :expenses, foreign_key: 'author_id', dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :update_allowed_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [:splash]
  # before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation)
    end
  end

  def after_sign_out_path_for(_resource_or_scope)
    new_user_session_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]

  def index
    @categories = current_user.categories.includes(:expenses)
    @total = sum_toatal
  end

  def show
    @transactions = @category.expenses.order(created_at: :desc)
  end

  def new
    @category = Category.new
  end

  def edit; end

  def create
    @category = Category.new(category_params)
    @category.user = current_user
    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_url, notice: 'Category was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: 'Category was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
    end
  end

  private

  def sum_toatal
    sum = 0

    @categories.each do |i|
      sum += i.expenses.sum(:amount)
    end
    sum
  end

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: %i[show edit update destroy]

  def index
    @expenses = current_user.expenses
  end

  def show; end

  def new
    @expense = Expense.new
    @categories = current_user.categories
  end

  def edit
    @expense = Expense.new
    @categories = current_user.categories
  end

  def create
    @expense = Expense.new(expense_params)
    @expense.user = current_user
    @categories = current_user.categories

    respond_to do |format|
      if @expense.save
        category = expense_params[:category_ids][1]
        format.html { redirect_to category_path(category), notice: 'Expense was successfully created.' }

      else
        format.html { render :new, status: :unprocessable_entity }

      end
    end
  end

  def update
    @expense = Expense.new(expense_params)
    @expense.user = current_user
    @categories = current_user.categories

    respond_to do |format|
      category = expense_params[:category_ids][1]
      if @expense.update(expense_params)
        format.html { redirect_to category_path(category), notice: 'Expense was successfully updated.' }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1 or /expenses/1.json
  def destroy
    @expense.destroy
    category = Category.find(params[:category_id])

    respond_to do |format|
      format.html { redirect_to category_path(category), notice: 'Expense was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_expense
    @expense = Expense.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def expense_params
    params.require(:expense).permit(:name, :amount, { category_ids: [] })
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def splash
    return unless current_user

    redirect_to categories_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    redirect_to categories_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/category_expenses_helper.rb
module CategoryExpensesHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>" class="text-with-icon flex">
  <p class="cat-img flex">
    <%=image_tag(category.icon, alt:category.icon, class: 'cat-icon')%>
  </p>
  <div class="cat-name c-flex">
    <p class="cat-title"> <%= category.name %></p>
    <p class="cat_date"><%=category.created_at %></p>
  </div>
</div>

app/views/categories/_form.html.erb
<div class="user-form-wrapper  c-flex">
 <%= form_with(model: category) do |form| %>
   <% if category.errors.any? %>
     <div style="color: red">
       <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

       <ul>
         <% category.errors.each do |error| %>
           <li><%= error.full_message %></li>
         <% end %>
       </ul>
     </div>
   <% end %>

   <div>
     <%#= form.label :name, style: "display: block" %>
     <%= form.text_field :name, placeholder: "Category Name"%>
   </div>

   <div>
     <%#= form.label :icon, style: "display: block" %>
     <%#= form.text_field :icon %>
   </div>
       <div class="cat-box-wrap c-flex">
         <p class="radio_text">Select an icon for category</p>

         <div class="check-boxes flex">
           <% Category::ICONS.each do |i| %>
             <div>
               <%= form.radio_button :icon, "#{i}.svg", id: i %>
               <label for="<%=i%>" class="custom-radio">
                <%=image_tag("#{i}.svg", alt:i, class: 'buttom_img')%>
             </div>
           <% end %>
         </div>
       </div>
  
   <div>
     <%= form.submit  class:'btn-blue' %>
   </div>
 <% end %>
</div>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<%= render 'share/nav', name: 'CATEGORIES', home: false%>
<div class = "total-buget flex">
  <h2 class="link-gray">Total Budget</h2>
  <h2 class="link-gray">$ <%=@total%></h2>
</div>
<div class= "category-wrapper">
  <p style="color: green"><%= notice %></p>

  <div id="categories c-flex">
    <% @categories.each do |category| %>
     <div class="individual-cat flex">
      <a href="<%= category_path(category) %>" class="cat-link flex">
        <%= render category %>
        <div class="cat">
           <p>$ <%=category.expenses.sum(:amount)%></p>
        </div>
      </a>
    </div>
    <% end %>
  </div>
  <div class="add-cat-wrapper flex">
    <%= link_to "New category", new_category_path, class: 'btn-blue add-cat' %>
  </div>
</div>

app/views/categories/new.html.erb
<%= render 'share/nav', name: 'NEW CATEGORY', home: false%>
<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path, class:'link-gray' %>
</div>

app/views/categories/show.html.erb
<%= render 'share/nav', name: 'TRANSACTIONS', home: false%>

<div class="category_wrapper">
   <div class="transaction_wrapper bline flex">
     <div class="text-with-icon border flex">
        <p class="cat-img flex">
         <%=image_tag(@category.icon, alt:@category.icon, class: 'cat-icon')%>
       </p>
       <div class="cat-name c-flex">
         <p class="cat-title "> <%= @category.name %></p>
         <p class="cat_date"><%=@category.created_at %></p>
       </div>
     </div>
     <div class="trans_details_summary c-flex">
         <%# <div> %>
            <p >$ <%= @transactions.sum(:amount)%></p>
         <%# </div> %>

         <div class= "trans-btn flex">
            <%= link_to "Edit", edit_category_path(@category), class:"button-link " %> | 
            <%= button_to "Delete", @category, method: :delete ,  class:"button-link del"%>
         </div>
     </div>
   </div>

   <div class="transactions_wrapper">
      <% @transactions.each do |item| %>
        <div class="transaction_list flex">
           <div class="trans-name_date c-flex"> 
             <p class=""><%=item.name%></p>
             <p class="cat_date"><%=item.created_at%></p>
           </div>
           <div class="individual_expenses_btn c-flex">
             <p> $ <%=item.amount%></p>
             <div class= "trans-btn flex">
              <%# <p><%= link_to "Edit", edit_expense_path(item), class:"button-link " %> 
              <p><%= button_to "Delete", item, method: :delete, class:"button-link del" %></p>
             </div>
           </div>
        </div>
      <% end %>
   </div>

  <div class="new_trans flex">
    <%= link_to "NEW TRANSACTION", new_expense_path , class:'signin link_btn_big'%>
  </div>

</div>

app/views/expenses/_expense.html.erb
<div id="<%= dom_id expense %>">
  <p>
    <strong>Name:</strong>
    <%= expense.name %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= expense.amount %>
  </p>

</div>

app/views/expenses/_form.html.erb
 <%= form_with(model: expense) do |form| %> 
<%#= form_with model: [ current_user, current_user.expenses.build ] do |form| %>
<%#= form_with model: [@expense, @expense.category_expenses.build ] do |form| %>
 
  <% if expense.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
        <% expense.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%# <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name , placeholder: "Name"%>
  </div>

  <div>
    <%# <%= form.label :amount, style: "display: block" %>
    <%= form.number_field :amount, placeholder: "Amount" %>
  </div>

    <div class="field c-flex">
      <p><%= form.label :category_ids, 'Select category(ies)' %></p>
      <%= form.collection_select :category_ids, @categories, :id, :name, {}, { multiple: true, required: true , class:"select-input"} %>
    </div>

  <div>
    <%= form.submit class:'btn-blue' %>
  </div>
<% end %>

app/views/expenses/edit.html.erb
<h1>Editing expense</h1>

<%= render "form", expense: @expense %>

<br>

<div>
  <%= link_to "Show this expense", @expense %> |
  <%= link_to "Back to expenses", expenses_path %>
</div>

app/views/expenses/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Expenses</h1>

<div id="expenses">
  <% @expenses.each do |expense| %>
    <%= render expense %>
    <p>
      <%= link_to "Show this expense", expense %>
    </p>
  <% end %>
</div>

<%= link_to "New expense", new_expense_path %>

app/views/expenses/new.html.erb
<%= render 'share/nav', name: 'TRANSACTIONS', home: false%>

<div class="user-form-wrapper  c-flex">
  <%= render "form", expense: @expense %>
</div>

app/views/expenses/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @expense %>

<div>
  <%= link_to "Edit this expense", edit_expense_path(@expense) %> |
  <%= link_to "Back to expenses", expenses_path %>

  <%= button_to "Destroy this expense", @expense, method: :delete %>
</div>

app/views/homes/splash.html.erb
<%= render 'share/nav', name: 'WELCOME', home: true %>

<div class="user-form-wrapper  c-flex">
    <div class = "title c-flex">
      <h2> BudgiSEE </h2>
    </div>


    <div class="c-flex">
      <%if !user_signed_in?%>
        <%= link_to 'LOG IN', user_session_path, class: 'signin' %>
        <%= link_to 'SIGN UP', new_user_registration_path , class: 'signup' %>
     <%else%>
        <%= link_to 'VIEW CATEGORIES', categories_path, class: 'signin' %>
     <%end%>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
   <div class="container c-flex c-flex-center">
     <%= yield %>
   </div>
  </body>
</html>

app/views/share/_nav.html.erb
<nav class='flex'> 
    <div>
     <% unless home %>
      <%= link_to image_tag("arrow-left.svg", class:'arrow'), categories_path, class: "arrow" %>  
     <% end%>
    </div>
    <header>
       <h1> <%= name %></h1>
    </header>
    <%if user_signed_in? %>
      <div class='profile flex'>
         <%#= button_to "Sign Out", destroy_user_session_path, method: :delete , class: "link" , id:'logout' %>
         <%= button_to image_tag('logout.svg', alt:'logout'), destroy_user_session_path, method: :delete , class: "link" , id:'logout' %>

      </div>
    <%else%>
       <div class='profile flex'>
       </div>
    <%end%>
</nav>